<?php

namespace TrackerBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use TrackerBundle\Entity\Project;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends EntityRepository
{
    public function getRootProjectIssues(Project $project)
    {
        $rootProjectIssues = $this->findBy([
            'project' => $project,
            'parentIssue' => null,
        ]);

        return $rootProjectIssues;
    }
}
